version: 0.2

# env:
#   parameter-store:
#     LOGIN_PASSWORD: "dockerLoginPassword"
#
phases:
  install:
    commands:
      - echo Entered the install phase...
      - gem install bundler
      - bundle install --path vendor/bundle
    finally:
      - echo This always runs even if the update or install command fails
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo This always runs even if the login command fails
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - bundle exec rspec RAILS_ENV=test
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - rm -rf vendor
      - rm -rf log
      - rm -rf tmp
artifacts:
  files:
    - ./*
  discard-paths: yes
# cache:
#   paths:
#     - '/root/.m2/**/*'
